---
- name: Install packages
  become: true
  apt:
      name:
      - gdb
      - gdb-multiarch
      - python3-pip
      - libcapstone3

- name: Install python packages
  become: true
  pip:
      executable: pip3
      name:
      - capstone
      - unicorn
      - keystone-engine
      - ropgadget
      - ropper
      - retdec-python

- name: Clone gef
  git:
      repo: https://github.com/hugsy/gef.git
      dest: "{{ansible_user_dir}}/.repositories/gef"

- name: Configure .gdbinit
  lineinfile:
      create: true
      path: "{{ansible_user_dir}}/.gdbinit"
      line: "{{item}}"
  with_items:
      - macro define offsetof(_type, _memb) ((long)(&((_type *)0)->_memb))
      - macro define containerof(_ptr, _type, _memb) ((_type *)((void *)(_ptr) - offsetof(_type, _memb)))
      - macro define thread_info() (*(struct thread_info*)((long)$rsp&~(0x2000-1)))
      - macro define task_struct() thread_info().task
      - set follow-fork-mode child
      - set disassembly-flavor intel
      - set auto-load safe-path /
      - source ~/.repositories/gef/gef.py
