---
- name: Add signing keys
  become: true
  apt_key:
      url: "{{item}}"
      state: present
  with_items:
      - "https://dl.google.com/linux/linux_signing_key.pub"
      - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"

- name: Add apt repositories
  become: true
  apt_repository:
      repo: "{{item}}"
      state: present
  with_items:
      - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      - "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib"

- name: Install packages
  become: true
  apt:
      name: "{{item}}"
      state: present
      update_cache: true
  with_items:
      - dkms
      - virtualbox-5.1
      - google-chrome-stable
      - jfsutils
      - ssh-server

- name: Install vagrant
  become: true
  apt:
      deb: "https://releases.hashicorp.com/vagrant/1.9.4/vagrant_1.9.4_x86_64.deb"

- name: Set git email
  git_config:
      scope: global
      name: user.email
      value: robert@the-playground.dk

- name: Set git user name
  git_config:
      scope: global
      name: user.name
      value: Robert Larsen

