---
- name: Add signing keys
  become: true
  apt_key:
      url: "{{item}}"
      state: present
  with_items:
      - "https://dl.google.com/linux/linux_signing_key.pub"
      - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
      - "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      - "https://keybase.io/hashicorp/pgp_keys.asc"

- name: Add apt repositories
  become: true
  apt_repository:
      repo: "{{item}}"
      state: present
  with_items:
      - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      - "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib"
      - "deb [arch=amd64] https://deb.nodesource.com/node_6.x {{ansible_distribution_release}} main"

- name: Install packages
  become: true
  apt:
      name: "{{item}}"
      state: present
      update_cache: true
  with_items:
      - dkms
      - virtualbox-5.1
      - google-chrome-stable
      - jfsutils
      - openssh-server
      - cryptsetup-bin
      - wipe
      - graphviz
      - ddd
      - doxygen

- name: Install vagrant
  become: true
  apt:
      deb: "https://releases.hashicorp.com/vagrant/1.9.5/vagrant_1.9.5_x86_64.deb"

- name: Set ssh dir permissions
  file:
      path: "{{ansible_user_dir}}/.ssh"
      state: directory
      mode: 0700

- name: ssh client config
  blockinfile:
      dest: "{{ansible_user_dir}}/.ssh/config"
      create: True
      block: |
        Host gogs.the-playground.dk
            Port 10022
            User git

- name: Know gogs.the-playground.dk
  lineinfile:
      dest: "{{ansible_user_dir}}/.ssh/known_hosts"
      create: True
      line: "{{item}}"
  with_items:
      - "|1|j5gochmZUabs7pVVoFX/Z61YsRg=|fgXFP+mcghMBT62xQ1a5WwKOw/U= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJw9lbWEFuKOmehtLzcP+gN2V+2fr/jwkSE6Mn+azUdK7reKm8hdvfOEiwC27zOhXysj/+TGQcOrjD7F1Lvu2JQ="
      - "|1|+5ngtb2l4HJLKgUGLuoIayHj11M=|b/9ZFQHewFtoPG5UVDQRyw3L9Jg= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJw9lbWEFuKOmehtLzcP+gN2V+2fr/jwkSE6Mn+azUdK7reKm8hdvfOEiwC27zOhXysj/+TGQcOrjD7F1Lvu2JQ="

- name: Set ssh file permissions
  file:
      path: "{{ansible_user_dir}}/.ssh/{{item}}"
      state: file
      mode: 0600
  with_items:
      - config
      - known_hosts
      - id_rsa

- name: Set git email
  git_config:
      scope: global
      name: user.email
      value: robert@the-playground.dk

- name: Set git user name
  git_config:
      scope: global
      name: user.name
      value: Robert Larsen

- name: Have my dotfiles
  git: 
      repo: https://github.com/RobertLarsen/dotfiles.git
      dest: "{{local_repositories_dir}}/dotfiles"

- name: Load local bash settings
  lineinfile:
      dest: "{{ansible_user_dir}}/.bashrc"
      line: ". {{local_repositories_dir}}/dotfiles/bashrc"
