---
- name: Add Microsoft repository key
  become: true
  apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc

- name: Microsoft Visual Studio Code repository
  become: true
  apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

- name: Microsoft Prod. repository for dotnet
  become: true
  apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ansible_distribution_version}}/prod {{ansible_distribution_release}} main"


- name: Add mono signing keys
  become: true
  apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF


- name: Add apt repositories
  become: true
  apt_repository:
      repo: "deb https://download.mono-project.com/repo/ubuntu vs-{{ansible_distribution_release}} main"


- name: Install packages
  become: true
  apt:
      update_cache: true
      name:
      - mono-devel
      - monodevelop
      - monodevelop-nunit
      - monodevelop-versioncontrol
      - monodoc-browser
      - packages-microsoft-prod
      - dotnet-sdk-2.2
